

---

- name: Update the system and install pre-requisites for k8s installation
  hosts: all
  max_fail_percentage: 0
  ignore_unreachable: false
  become: true
  tasks:

  - name: Update the system
    package:
      update_cache: true
      upgrade: dist

  - name: Pre-requisites for k8s installation (common for all nodes in the cluster)
    script: ../Bash/install_k8s_preqs.sh


- name: Initialize k8s cluster
  hosts: master
  ignore_unreachable: false
  become: true
  tasks:

  - name: Kubeadm init
    shell: kubeadm init --apiserver-advertise-address $(curl http://icanhazip.com/) --pod-network-cidr 10.244.0.0/16
    register: kubeadm_init_stdout

  - name: Save kubeadm_init_stdout to file
    copy:
      content: '{{ kubeadm_init_stdout.stdout }}'
      dest: kubeadm_init_stdout.txt

  - name: Pull the stdout of kubeadm init (save on my local machine)
    synchronize:
      mode: pull
      src: kubeadm_init_stdout.txt
      dest: .

  - name: Creating .kube dir
    file:
      dest: "/home/{{ ansible_user }}/.kube"
      state: directory

  - name: Copy admin.conf to .kube/config
    copy:
      remote_src: true
      src: /etc/kubernetes/admin.conf
      dest: "/home/{{ ansible_user }}/.kube/config"
      owner: root
      group: root
      mode: "0644"

  - name: Applying network plugin (Flannel)
    command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    become: false

  
# grep -A4 'Then you can join any number of worker nodes by running the following on each as root' test.txt | tail -n 2

