apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-deployment
spec:
  template:
    metadata:
      name:  endpoint-pod
      labels:
        app: metacrawler
        type: backend
    spec:
      containers:
        - name: endpoint-container
          image: ehsanu/metacrawler
  replicas: 2
  selector:
    matchLabels:
      type: backend