apiVersion: v1 
kind: Service
metadata:
  name: endpoint-svc
  labels:
    app: metacrawler
    type: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    type: backend
