apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
spec:
  template:
    metadata:
      name:  {{ .Values.appName }}
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: endpoint-container
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
      imagePullSecrets:
        - name: regcred
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}



