apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  ports:
    - name: endpoint
      port: 80
      targetPort: 80
  selector:
    app: {{ .Values.appName }}



